name: Ping API warm-up

on:
  workflow_dispatch:
    inputs:
      base_url:
        description: 'Deployment base URL (e.g., https://your-app.vercel.app)'
        required: true
      delay_ms:
        description: 'Delay between pings (ms)'
        required: false
        default: '5000'
  # schedule:
  #   - cron: '*/15 * * * *' # disabled on Hobby

jobs:
  warm:
    runs-on: ubuntu-latest
    steps:
      - name: Ping endpoints
        shell: bash
        run: |
          set -e
          BASE="${{ github.event.inputs.base_url }}"
          DELAY="${{ github.event.inputs.delay_ms }}"
          if [ -z "$BASE" ]; then echo "base_url input is required"; exit 1; fi
          if [ -z "$DELAY" ]; then DELAY=5000; fi
          urls=(
            "$BASE/api/world?page=1"
            "$BASE/api/pk?page=1"
            "$BASE/api/pk?scope=from&page=1"
            "$BASE/api/pk?scope=about&page=1"
            "$BASE/api/trending/topics?region=pk"
          )
          echo "Warming $BASE with delay ${DELAY}ms"
          for u in "${urls[@]}"; do
            echo "GET $u"
            # Do not fail the whole job on a single endpoint failure or 429
            curl -fsS "$u" || echo "Warn: request failed (continuing)"
            sleep $((DELAY/1000))
          done
